spring:
# to make 04_Auth_Service appln. as client to Admin server appln which is running on port no:1111 
  boot:
    admin:
      client:
        url: http://localhost:1111/
      
#DB configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
#Congigure actuator endpoint urls
management:
  endpoints:
    web:
      exposure:
        include: '*'
  
server:
  port: 8081
